name: Run Performance Audit
on:
  push:
    branches:
      - 'master'
env:
  PLATFORMSH_CLI_TOKEN: ${{ secrets.PLATFORMSH_CLI_TOKEN }}
  WEBMASTER_GITHUB_ACTIONS_TOKEN: ${{ secrets.WEBMASTER_GITHUB_ACTIONS_TOKEN }}
  PLATFORM_PROJECT_ID: ${{ secrets.PLATFORM_PROJECT_ID }}
  PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
jobs:
  deploy_platform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Psh CLI
        run: |
          curl -sS https://platform.sh/cli/installer | php

      - name: Load certificate
        run: ~/.platformsh/bin/platform ssh-cert:load -y -vv

      - name: Add Psh to trusted keys
        continue-on-error: true
        run: |
          for ip in $(dig @8.8.8.8 git.us-2.platform.sh git.us.platform.sh git.us-4.platform.sh +short); do \
            ssh-keyscan git.us.platform.sh, git.us-2.platform.sh, git.us-4s.platform.sh,$ip; \
            ssh-keyscan $ip; \
          done 2>/dev/null >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts

      - name: Spin up environment
        run: |
          ~/.platformsh/bin/platform project:set-remote ${{ secrets.PLATFORM_PROJECT_ID }}
          ~/.platformsh/bin/platform environment:activate ${GITHUB_REF#refs/heads/} --project=${{ secrets.PLATFORM_PROJECT_ID }}
          ~/.platformsh/bin/platform environment:push -vv --target=${GITHUB_REF#refs/heads/} --project=${{ secrets.PLATFORM_PROJECT_ID }} --environment=${GITHUB_REF#refs/heads/} --force

  test_performance:
    runs-on: ubuntu-latest
    needs: deploy_platform
    steps:
      - uses: actions/checkout@v2
      - name: Install Psh CLI
        run: |
          curl -sS https://platform.sh/cli/installer | php
          ~/.platformsh/bin/platform project:set-remote ${{ secrets.PLATFORM_PROJECT_ID }}
      - name: running sitespeed.io container with arguments and optional Docker options
        run: docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:21.6.1 -b chrome --outputFolder sitespeed-result --budget.configPath .github/config/main_performance.json --budget.output junit https://$( ~/.platformsh/bin/platform domains --format=plain --no-header --columns=name ) -n 5
      - name: Archive SiteSpeed Results
        uses: actions/upload-artifact@v2
        with:
          name: sitespeed-result
          path: sitespeed-result  
