name: Run Performance Audit
on:
  push:
    branches:
      - 'master'
env:
  PLATFORMSH_CLI_TOKEN: ${{ secrets.PLATFORMSH_CLI_TOKEN }}
  WEBMASTER_GITHUB_ACTIONS_TOKEN: ${{ secrets.WEBMASTER_GITHUB_ACTIONS_TOKEN }}
  PLATFORM_PROJECT_ID: ${{ secrets.PLATFORM_PROJECT_ID }}
  PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
jobs:
  deploy_platform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # - name: Install Psh CLI
      #   run: |
      #     curl -sS https://platform.sh/cli/installer | php

      # - name: Load certificate
      #   run: ~/.platformsh/bin/platform ssh-cert:load -y -vv

      # - name: Add Psh to trusted keys
      #   continue-on-error: true
      #   run: |
      #     for ip in $(dig @8.8.8.8 git.us-2.platform.sh git.us.platform.sh git.us-4.platform.sh +short); do \
      #       ssh-keyscan git.us.platform.sh, git.us-2.platform.sh, git.us-4s.platform.sh,$ip; \
      #       ssh-keyscan $ip; \
      #     done 2>/dev/null >> ~/.ssh/known_hosts
      #     cat ~/.ssh/known_hosts

      # - name: Spin up environment
      #   run: |
      #     ~/.platformsh/bin/platform project:set-remote ${{ secrets.PLATFORM_PROJECT_ID }}
      #     ~/.platformsh/bin/platform environment:activate ${GITHUB_REF#refs/heads/} --project=${{ secrets.PLATFORM_PROJECT_ID }}
      #     ~/.platformsh/bin/platform environment:push -vv --target=${GITHUB_REF#refs/heads/} --project=${{ secrets.PLATFORM_PROJECT_ID }} --environment=${GITHUB_REF#refs/heads/} --force

  test_prep:
    runs-on: ubuntu-latest
    needs: deploy_platform
    steps:
      - uses: actions/checkout@v2
      # - name: Install Psh CLI
      #   run: |
      #     curl -sS https://platform.sh/cli/installer | php
      #     ~/.platformsh/bin/platform project:set-remote ${{ secrets.PLATFORM_PROJECT_ID }}

      # - name: Setup node
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '14.x'
      #     registry-url: 'https://npm.pkg.github.com'
      # - run: npm install
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.WEBMASTER_GITHUB_ACTIONS_TOKEN }}
      # - run: npm install -g sitemap_utils jsonlint sitemap commander
      
      - name: Download Sitemap
        run: |
          flatten_sitemap --sitemap https://$( ~/.platformsh/bin/platform domains --format=plain --no-header --columns=name )/sitemap_index.xml --config .github/sitemap.json --limit 20 --randomize
          cat .github/sitemap.json

      - name: Archive sitemap
        uses: actions/upload-artifact@v2
        with:
          name: sitemap
          path: .github/sitemap.json

  lighthouse_master:
    runs-on: ubuntu-latest
    needs: test_prep
    steps:
      - uses: actions/checkout@v2
      - name: Install Psh CLI
        run: |
          curl -sS https://platform.sh/cli/installer | php
          ~/.platformsh/bin/platform project:set-remote ${{ secrets.PLATFORM_PROJECT_ID }}
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'
      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.WEBMASTER_GITHUB_ACTIONS_TOKEN }}
      - run: npm install -g lighthouse-batch
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: sitemap
      - name: running sitespeed.io container with arguments and optional Docker options
        run: docker run --shm-size=1g --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:21.6.1-plus1 https://soblu50.colby.edu --plugins.add analysisstorer --plugins.add /lighthouse 
        # docker run --shm-size=1g --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:21.6.1-plus1 https://www.sitespeed.io/ --plugins.add analysisstorer --plugins.add /lighthouse --outputFolder sitespeed-result --budget.configPath .github/lighthouse/main.json --budget.output junit -b chrome  -n 3

      - name: Archive SiteSpeed Results
        uses: actions/upload-artifact@v2
        with:
          name: sitespeed-result
          path: sitespeed-result  
